### ISSUE TITLE
Licensing? 

### ISSUE THREAD

**Issue by ExoticMarbles** [zabi94/ExtraAlchemy#100]
What are your rules for using your code in our own mods? You'd of course get credit.

**Comment by zabi94** [comment]
I'm fine with people looking at it for learning purposes, or to see how I approached and/or solved a problem (eg: potion recipe registration).

Ports of assets and code (full or partial) to forge based environments is strictly forbidden (I generally discourage other forms of copy pasting code as well because they don't allow you to understand how it works, but that's my opinion).

I guess it depends on what code you want to use, and for what kind of mod

**Comment by ExoticMarbles** [comment]
Understood. No "forge"ry allowed. Thanks much!
