### ISSUE TITLE
Bug with growing and shrinking potion Fabric 1.16.5

### ISSUE THREAD

**Issue by MooreGaming1324** [zabi94/ExtraAlchemy#115]
**Describe the bug**
being 2 blocks tall on client and 1 block tall on server

**To Reproduce**
1. Set your pehkui scale to something small, or drink a shrinking potion
2. open your inventory or any item. I believe this only happens on the server however
3. your scale will be set to 2 blocks visually, yet on the server is 1 block
4. relog and your scale will go back to the scale in step 1.

**Expected behavior**
I expect it to stay small, and not desync from the server

**Screenshots**
![2021-07-26_14 23 57](https://user-images.githubusercontent.com/82669671/127039417-2e834004-5f71-4298-8f5d-9074366ea8c7.png)

![image](https://user-images.githubusercontent.com/82669671/127039492-eea339e6-8056-4c50-8a88-d3e1bc8eab3b.png)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log: 
 - Mod List: https://pastebin.com/U9u3z5X1
 - Extra Alchemy Config: https://pastebin.com/MXGdtPDe

**Environment (please complete the following information):**
Versions in Mod list, fabric launcher 0.11.6
 - System: Windows 10
 - Installation type: Computer Server

**Comment by zabi94** [comment]
I must have missed this.
Seems like this is an issue on Pehkui's side. I guess that removing extra alchemy and setting the size through pehkui still desyncs.
In these 9 months the issue was probably fixed, I imagine. 

I'll close the issue for now, if it still happens and removing extra alchemy fixes the problem, let me know.
