### ISSUE TITLE
crash with version on 1.11.2

### ISSUE THREAD

**Issue by 0Navis0** [zabi94/ExtraAlchemy#13]
I get this crash at startup with last version of Extra Alchemy on 1.11.2 https://pastebin.com/MfyGtRLE

**Comment by zabi94** [comment]
Please, use the form that appears when you open a new issue. I can't fix if the data I need is missing. 

Also, from the log you provided I can see 3 things: 
1) There are no reference to extra alchemy in the crash
2) You are missing compatlayer 0.2.7+ apparently, but that does not cause this crash, it should warn you with a nice and clear message
3) It looks like a problem with better foliage? Does it start if you remove the mod? 

If the problem persists, please open a new issue and compile all fields, they are necessary

**Comment by 0Navis0** [comment]
#### Type of Issue (Bug / Crash / Suggestion / Translation / ...):
>https://pastebin.com/MfyGtRLE

#### Version of the mod or build number:
>extraalchemy-0.3.1.2

#### Minecraft Version (1.9.4, 1.10, 1.10.2...):
>1.11.2
>Forge 13.20.0.2285

#### Description of the issue (or what were you doing when it crashed):
>The crash occurs at the startup of Minecraft during the first step when it constructs the mod.

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>https://pastebin.com/Zimue6VR

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>I use my own modpack ULTRA, but here it's the beta version on 1.11.2 still not published on Curse because there is no enough mods and it's still kinda buggy and early.

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>https://pastebin.com/eJVEt6YH

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>Jave 8
>Windows 10

#### Other information that you think might be useful:
>Remove Better Foliage doesn't change anything, and the version of Compat Layer you tell me to use doesn't exist, at least not on Curse, the last version on Curse is 0.2.5.

**Comment by zabi94** [comment]
Does the issue disappear if you remove just extra alchemy? The issue doesn't seem to be its fault, it happens in a phase I never hooked into. 
Compat Layer 0.2.7 links are in the 0.3.1.1 file changelog, they are not on curseforge yet but they exist, I'll post links in the description page as soon as I can. Please try to install it and see if the issue disappears. 
Remember that this version is not meant for public mod packs yet, it is extremely experimental, plus, since compat layer isn't out yet, you can't fulfill the dependencies in the curse client.

**Comment by 0Navis0** [comment]
Yeah the issue is linked to extra alchemy, the issue doesn't happen when the mods isn't present. But I think it's linked to the fact I don't use the good version of Compat Layer, I use the last on on Curse and not the one your mod use. So your mod try to load a mod which doesn't exist and then crash.

**Comment by zabi94** [comment]
The point is that the crashlog shows that the crash happens when Minecraft is preloading block models, and it's weird. My mod isn't even in the stack when it crashes. 
When compatlayer is missing it doesn't crash at all, it just shows the message and close the game. 
Please, let me know if the correct version of CL solves the crash, but that would be so weird tbh

**Comment by 0Navis0** [comment]
It works now with the new version of Compat Layer. It was what I thought, your mod tried to load a mod which didn't exist and then crash.

**Comment by zabi94** [comment]
The problem is that it shouldn't crash, this is still a bug. What should happen when compatlayer is missing is that minecraft should show you this screen when initializing the game:

![screenshot](http://zabi.altervista.org/minecraft/extraalchemy/Misc/screen1.png)

Reopening until I figure out what's crashing

**Comment by zabi94** [comment]
Compat layer no longer needed
