### ISSUE TITLE
Crash on searching potion in inventory

### ISSUE THREAD

**Issue by Tototi1** [zabi94/ExtraAlchemy#22]
Compile the following template. Fields marked with (*) are mandatory, Fields with (-) are optional, Fields with (!) are mandatory in case of crash or bug

---

#### Type of Issue/Request (Bug / Crash / Suggestion / Translation / ...):
>(*)
Crash
---

#### Version of the mod or build number:
>(*)
0.3.3.1
---

#### Are you a Single Player, a Multiplayer Client (You are a player in a server) or Server Side?:
>(*)
Multiplayer Client
---

#### Minecraft Version (1.9.4, 1.10, 1.10.2, 1.11.2...):
>(*)
1.10.2
---

#### Description (or what were you doing when it crashed):
>(*)
I see a potions and i crash
---

#### [Pastebin](http://pastebin.com) of the log (fml-client-latest.log from your instance/logs folder):
>(!)
https://pastebin.com/SEMqnFXg
---

#### ModPack (or list of mods via [Pastebin](http://pastebin.com). If using a modified modpack, write *BOTH* the modpack AND the link to the _full_ mod list):
>(!)
https://pastebin.com/uqJPLPAc
---

#### [Pastebin](http://pastebin.com) of the config file (extraalchemy.cfg from your instance/config folder):
>(!)
https://pastebin.com/LTSMrijk
---

#### OS and Java version (Java8 + Windows10 / Java7 + MacOS / ...):
>(!)
Java8 + Windows10
---

#### Other information that you think might be useful:
>(-)

**Comment by zabi94** [comment]
The bug has been fixed in updated versions for 1.12.2. Unfortunately
support for older minecraft versions has been dropped.
Closing

Il 18 ott 2017 15:10, "Tototi1" <notifications@github.com> ha scritto:

**Comment by Tototi1** [comment]
You don't have a 1.10.2 version ?

**Comment by zabi94** [comment]
Not of this fix. You could try and disable rustic integration from config
(2 options to disable in total), but I don't think it will fix it.
The bug depends on an interaction bug with the rustic mod and its potions
(on my side, the fault is still extra alchemy)

Il 18 ott 2017 15:15, "Tototi1" <notifications@github.com> ha scritto:

You don't have a 1.10.2 version ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zabi94/ExtraAlchemyIssues/issues/22#issuecomment-337586605>,
or mute the thread

**Comment by Tototi1** [comment]
Okay, i deleted rustic an i see.
Thank you
