### ISSUE TITLE
[1.12.2] How do I add brewing recipes for custom potions?

### ISSUE THREAD

**Issue by jonqrandom** [zabi94/ExtraAlchemy#24]
in my recipes.zs i have
    `val levitationPotion = <minecraft:potion>.withTag({Potion:"crafttweaker:levitation", CustomPotionEffects: [{Ambient: 0 as byte, CurativeItems: [{id: "minecraft:milk_bucket", Count: 1 as byte, Damage: 0 as short}], ShowParticles: 1 as byte, Duration: 200, Id: 25 as byte, Amplifier: 0 as byte}]});`
which i can set as the output from a normal craft, and gives the expected 10 seconds of levitation 1. in extra_alchemy_recipes.cfg i have
    `minecraft:awkward & nex:food_meat_ghast_cooked = crafttweaker:levitation`
which doesn't even allow me to insert the ghast meat into the stand's input. if i replace "crafttweaker:levitation" with "enderzoo:floating" i can insert the ghast meat, and brew the potion from the enderzoo mod.
what nbt tags etc, do i need to set to allow extra alchemy to "see" my custom potion and set a brewing recipe for it, please?

**Comment by zabi94** [comment]
I believe that craft tweaker does something weird with potiontypes. In the
config there is an option to log all the valid potiontypes on start-up, you
can try and see if the name gets changed to something else

Il 19 nov 2017 21:49, "jonqrandom" <notifications@github.com> ha scritto:

**Comment by jonqrandom** [comment]
whatever i name the potion in `.withTag({Potion:""})`, it doesn't show up in your log, or in /tellme's list of potiontypes. it still has the tag set correctly in game, the potion itself works, but it's not showing up as a potiontype. it doesn't help to use `itemUtils.createPotion()`, either.
is there a registry of potiontypes? and if there is, and that's what you're checking, how would i add my custom potion to it? i don't see anything about this in the crafttweaker docs :/

**Comment by zabi94** [comment]
The problem here is how you are creating the potion. Using the withTag function you are creating a potion that has a custom effect, instead of adding a new PotionType into the registry (which is the only way my mod can load new recipes). I quickly read through the CraftTweaker page to see if there was a way to add them, but it doesn't look like it. 
I suggest going to their github page and opening a new issue requesting the option, since non-potionType custom recipes are out of this mod's scope

**Comment by jonqrandom** [comment]
okies, thanks anyway!
