### ISSUE TITLE
Potions of Returning just turn into glass bottles and don't do anything

### ISSUE THREAD

**Issue by Ecorous** [zabi94/ExtraAlchemy#84]
**Describe the bug**
Potions of Returning just turn into glass bottles 

**To Reproduce**
I don't know

**Expected behavior**
For it to bring me to my spawn

**Screenshots**

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - latest.log:  Can't right now
 - Mod List: Too long
 - Extra Alchemy Config: Server config, can't see it

**Environment (please complete the following information):**
 - Mod Version: *shrug*
 - MC Version: 1.16.1
 - Fabric Version: *shrug*
 - Fabric API version: *shrug*
 - System: Windows 10
 - Installation type: Server hosting 

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
I need to have all the data you shrugged and the very long mod list. That's key information to find the problem, since normally the potion works.

You can find mod versions by going into the mods section in your game, and for the mod list you can just take a screenshot or two of your mods folder contents

**Comment by Ecorous** [comment]
The modpack is broken now, doesn't matter
